.gitignore
botany_importer.py
botany_importer_config.template.py
client_tools.py
gen_import_utils.py
ich_importer_config.template.py
ichthyology_importer.py
image_client.py
importer.py
iz_importer.py
iz_importer_config.template.py
monitoring_tools.py
monitoring_tools_derived.py
picturae_config.template.py
picturae_csv_create.py
picturae_importer.py
picturae_readme.txt
specify_db.py
sql_csv_utils.py
tests/taxon_tree_dump.sh
tests/test_sql_tools.py
tests/test_taxontree.py

summary: changed the email batch reporting from `mutt` to `smtp` ,  encoded images with cid in order from proper embedding in emails.  Due to changes in monitoring_tools.py , changed the config templates, and how the monitoring_tools are executed form each importer.py file.
Files, changed: 
-monitoring_tools.py
-botany_importer_config.template
-ich_importer_config.template
-iz_importer_config.template
-ich_importer_config.template
-iz_importer
-botany_importer
-iz_importer
-ich_importer
-picturae_importer

Picturae import

---

PIC_undo_batch.py
client_tools.py
image_client.py
image_db.py
importer.py
monitoring_tools_derived.py
picturae_importer.py
sql_csv_utils.py

-Removed some old changes to the command line argparse allowing for data or image only purges.
-changed all interactions with image_db  to interactions with web asset server api.
-discovered and fixed an issue in the email html template, where one of the summary terms wasn't parsing correctly.

added image client api compatability ot PIC_undo

---

botany_importer.py
picturae_importer.py
sql_csv_utils.py

-in picturae_importer changed itterows to itertuples in order to improve looping speed. Not game changing,  but shaved about 2 seconds off for a sample size of 6 rows, so could add up for larger imports
-removed redundant logger statement to reduce command line clutter in insert table record

changed iterrows to itertuples to improve speed , reduce function size. 

---

.gitignore
botany_purger.py
config_collections.template.json
convert_local_to_remote_images_ich.py
ichthyology_importer.py
image_client.py
importer.py
iz_importer.py
monitoring_tools.py
picturae_importer.py

added optional config to image_server to populate image lists.
added separate htmls for each collection to avoid conflicts
added seperate html folder.
added extra config term to find html path

added collection level html reports to avoid conficts

---

README.md

pretty simple PR, just added a hyperlink the the readme + updated the readme to reflect some changes in client tools.

added hyperlink to readme to doc, and new client tools flags

---

README.md
botany_importer.py
ichthyology_importer.py
image_client.py
importer.py

changes:
image_client: 
-added function to importer.py, that now checks if there are base image file paths with same barcode, which defers to .jpg if both jpg and tif.
-now uses original filepath instead of real filepath, for monitoring report.
colllections imports:
-added the new importer method to ingest process.
Readme.md: corrected some commands in the quoted code snippets.

added function to remove duplicate barcodes on import, and updated monitoring report

---

.gitignore
BOT_database_updater.py
botany_importer.py
client_tools.py
config_files/botany_pic_config.template.py
gen_import_utils.py
image_batch_resizer/img_batch_resizer.py
importer.py
monitoring_tools.py
picturae_importer.py
sql_csv_utils.py
string_utils.py
taxon_parse_utils.py
taxon_tools/BOT_TNRS.py
tests/pic_importer_test_class_lite.py
tests/test_agent_list.py
tests/test_database_updater.py
tests/test_populate_fields.py
tests/test_taxontree.py

files changed:
-image_batch_resizer --> moved to subdirectory, improvements to efficiency
-picturae_importer --> changes to data import process to fit new data formats , improved parsing of agent names, and taxonomic names.
-sql_csv_utils, gen_import_utils, string_utils: removed un-needed utils, and changed function to better fit new data formats and specify DB requirements.
-BOT_database_updater.py: improved guardrails  on locality and locality detail tables, during update process.
-tests/ : updated unittests to reflect current state of functions.

re-organized importer for new data format, improvements to certain steps of import process.

---

client_tools.py
image_client.py
importer.py
monitoring_tools.py
picturae_importer.py
tests/botany_importer_test_class.py
tests/deprecated.test_botany_importer.py
tests/pic_importer_test_class.py
tests/pic_importer_test_class_lite.py
tests/test_agent_list.py
tests/test_database_updater.py
tests/test_file_hide.py
tests/test_populate_fields.py
tests/test_sql_tools.py
tests/test_taxontree.py

files changed: 
client_tools.py : removed unnecessary path and regex operations, paths are now read and concatenated using "image_path" column in csvs + config terms. 
picturae_importer.py: split off operations that read and process csv files into a seperate function in init, allows for easier testing without having to create dummy csvs for every unittests.
tests/pic_importer_test_class.py: created pared down test version of process csvs function
tests/pic_importer_test_class_lite.py: created pared down test version of process csvs function

changed picturae_import to read combined batch csvs , and changed some path variables.

---

BOT_database_updater.py
PIC_database_updater.py
PIC_undo_batch.py
botany_importer.py
client_tools.py
ichthyology_importer.py
importer.py
monitoring_tools.py
monitoring_tools_derived.py
picturae_importer.py
requirements.txt
sql_csv_utils.py
tests/database_updater_test_class.py

files changed:
picturae_importer.py: date arg no longer required
client_tools.py: uses different ./tmp_jpg folders for active vs passive imports on picturae to avoid clashing.
sql_csv_tools.py: agent config term no longer hardcoded, now is function param
TMP_JPG param moved to configs to allow for it to be changed in client_tools.py

changed ./tmp_jpg folder to config setting to avoid active vs passive imports clashing, removed hardcoded agent id from sql tools.

---

attachment_utils.py

-changes title to display barcode on specify7 instead of URL

adding in title based on basename to make display title look nicer on specify

---

iz_importer.py

This PR includes cleanup of duplicate code in iz_importer.py.

Cleanup of duplicate code

---

image_client.py
importer.py
iz_importer.py

This pull request fixes the multiple import bug.

Fixed multiple import bug

---

iz_importer.py

Merged from master and fixed issues in iz_importer.py

Fix issues in iz_importer.py

---

attachment_utils.py
importer.py
iz_importer.py
nightly_sync.py

Please review the changes related to the bad redacted check.

Fixed bad redacted check

---

importer.py
iz_importer.py

This pull request includes the following changes:\n- Added support for converting DNG files to JPG.\n- Optimized the convert_image_if_required function to handle DNG files.\n- Ensured that small images are skipped appropriately.

Support DNG file conversion

---

importer.py

This PR addresses the DNG conversion process, adding another step as required.

DNG conversion requires another step

---

iz_importer.py

Merge iz_ingest to master

---

iz_importer.py

Fixing the no-key case and getting all the numbers correctly

Fixing the no-key case and getting all the numbers correctly

---

iz_importer.py

Remove non functional photoshop:copyright flag and blanking exif:credit.

Merge iz_ingest into master

---

iz_importer.py

IZ exif ingest failure

---

import_check.sh

change to check import logic

---

iz_importer.py

Merge iz_ingest branch into master

---

sql_csv_utils.py
tests/sqlite_csv_utils.py

It may be better to change the settings on my SQLite deploy in tests than make a derived version in sqllite_csv_utils

parallel change to taxon_get, sqlite case sensitive version of taxon_get

---

Jenkinsfile
importer_jenkins_setup.sh

changes:
--fetch and hard reset to jenkins file, checkout scm was not enough to pull most recent changes.
-- safe directory permissions to working directory
-- force init to submodule

update of jenkins setup permissions

---

string_utils.py

spot fix to variable referenced before assignment error.

variable referenced before assignment

---

picturae_importer.py
tests/pic_importer_test_class_lite.py
tests/test_database_updater.py
tests/test_populate_fields.py
tests/test_taxontree.py

Don't merge this yet, I am using it to test the PR pipeline webhooks on the new jenkins

added label data field for text overflow

---

picturae_importer.py

spot fix to add mass digitzation note to all future active imports.

added mass digitization note to remarks section

---

PIC_undo_batch.py
db_utils.py
image_client.py
image_db.py
sql_csv_utils.py
temp_utility_scripts/remove_incomplete_attachments.py

files changed:
db_utils.py: removed references to settings. Reorganized try except logic on get_one_record to avoid unread results error, copied logic to seperate get_records function.
image_client.py: changed log message and log message order , remove redundant variables in requests_with_retries.
image_db.py: copied parameterized logic from web asset server changes.
sql_csv_utils.py: some minor improvements to get one match, param names, removing defunct package imports.

Prod edits

---

image_client.py

request_with_retries changes: 
- moved the timeout check to be at the beginning of the while loop, 
- moved the  sleep before the increase to timeout interval for intended behavior
- renew server token during each retry

renewed token for request with retries

---

attachment_utils.py
botany_importer.py
db_utils.py
importer.py
iz_importer.py
monitoring_tools.py
sql_csv_utils.py

Parameterizartion of core importer functions

paramaterized core importer and attachment sql

---

docs/iz_importer_casiz.md
docs/iz_importer_copyright.md

document IZ importer rules to extrac CASIZ and Copyright

docs to explain IZ importer CASIZ and Copyright extraction rules

---

.github/workflows/ci.yml
.gitmodules
attachment_utils.py
importer_jenkins_setup.sh
iz_importer.py
requirements.txt
specify_constants.py
tests/iz_importer_tests/test_load_files.py

remove the submodule of metadata_tools and switch to pypi package

remove submodule of metadata_tools
